/// The game's sound effects, and the seam that lets everything else stay
/// deaf.
///
/// Nothing in the game talks to an audio library. Components and scenes talk
/// to [AudioOut], which has exactly one real implementation and one silent
/// one — so tests make no noise, a platform with no audio support is not a
/// crash, and swapping the backend later touches one file.
///
/// This is the same reasoning as the input abstraction the plan insists on:
/// gameplay code should not know what platform it is on, and it should not
/// know what is playing its sounds either.
library;

/// A sound the game can make.
///
/// The files are generated by `tools/sfx.py`, not recorded — there is no
/// audio artist on this project. Retune them by editing that script and
/// running it again; do not hand-edit the wavs, they are build output.
enum Sfx {
  step1('step_1.wav', voices: 4),
  step2('step_2.wav', voices: 4),
  step3('step_3.wav', voices: 4),
  jump('jump.wav'),
  land('land.wav'),
  plate('plate.wav'),
  door('door.wav');

  const Sfx(this.file, {this.voices = 2});

  /// Path relative to `assets/audio/`.
  final String file;

  /// How many copies of this sound may be in the air at once.
  ///
  /// This is a budget, not a preference. An implementation that builds a fresh
  /// audio player per sound works fine for a minute and then stops working:
  /// measured in a browser, fifteen seconds of running created eighty-eight
  /// players, and somewhere past the fiftieth the browser quietly stopped
  /// playing them at all. Footsteps get the most because they fire four times
  /// a second.
  final int voices;

  /// The footstep variants, in the order they are cycled. One footstep sample
  /// four times a second is a woodpecker.
  static const List<Sfx> steps = [Sfx.step1, Sfx.step2, Sfx.step3];
}

/// Somewhere for sounds to go.
abstract interface class AudioOut {
  /// Loads every sound up front. A sound fetched at the moment it is needed
  /// arrives after the moment it was needed.
  Future<void> preload();

  /// Plays [sfx] at [volume] (0 to 1). Fire and forget: a sound that fails to
  /// play must never interrupt a frame.
  void play(Sfx sfx, {double volume});
}

/// An [AudioOut] that does nothing.
///
/// The default everywhere, so a scene is silent until something deliberately
/// gives it a voice. Tests use it without asking.
class SilentAudio implements AudioOut {
  const SilentAudio();

  @override
  Future<void> preload() async {}

  @override
  void play(Sfx sfx, {double volume = 1}) {}
}
